#!/usr/bin/env python3
"""Generates src/unicode_data.cpp.

The Llama 3 pretokenizer regex is written in terms of the Unicode character
classes \\p{L} and \\p{N}. Deciding whether a codepoint is a letter or a number
needs the Unicode general category table, which is far too large to write by
hand, so this script emits it as sorted codepoint ranges that the tokenizer
binary-searches. Run it after a Python upgrade to refresh the tables:

    python3 tools/gen_unicode_data.py
"""

import sys
import unicodedata
from pathlib import Path

MAX_CODEPOINT = 0x110000


def ranges_for(categories):
    """Collapses every codepoint in `categories` into sorted inclusive ranges."""
    out = []
    start = None
    for cp in range(MAX_CODEPOINT):
        inside = unicodedata.category(chr(cp)) in categories
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CODEPOINT - 1))
    return out


def emit_table(name, ranges, per_line=4):
    lines = [f"const CodepointRange k{name}Ranges[] = {{"]
    for i in range(0, len(ranges), per_line):
        chunk = ranges[i:i + per_line]
        body = " ".join(f"{{0x{lo:05X}, 0x{hi:05X}}}," for lo, hi in chunk)
        lines.append("    " + body)
    lines.append("};")
    return "\n".join(lines)


def main():
    letters = ranges_for({"Lu", "Ll", "Lt", "Lm", "Lo"})
    numbers = ranges_for({"Nd", "Nl", "No"})

    out = Path(__file__).resolve().parent.parent / "src" / "unicode_data.cpp"
    with out.open("w") as f:
        f.write(f"""// Generated by tools/gen_unicode_data.py from Unicode {unicodedata.unidata_version}.
// Do not edit by hand.
#include "unicode_data.h"

#include <algorithm>
#include <cstddef>

namespace lcr {{
namespace {{

struct CodepointRange {{
  uint32_t lo;
  uint32_t hi;
}};

// Sorted, non-overlapping, and non-adjacent, so a binary search on `lo` is
// enough to answer membership.
template <size_t N>
bool contains(const CodepointRange (&table)[N], uint32_t cp) {{
  const CodepointRange* it = std::upper_bound(
      table, table + N, cp,
      [](uint32_t value, const CodepointRange& r) {{ return value < r.lo; }});
  if (it == table) return false;
  --it;
  return cp <= it->hi;
}}

// General categories Lu, Ll, Lt, Lm, Lo. This is regex \\p{{L}}.
{emit_table("Letter", letters)}

// General categories Nd, Nl, No. This is regex \\p{{N}}.
{emit_table("Number", numbers)}

}}  // namespace

bool is_letter(uint32_t cp) {{ return contains(kLetterRanges, cp); }}
bool is_number(uint32_t cp) {{ return contains(kNumberRanges, cp); }}

// The Unicode White_Space property, which is what the regex crate behind the
// Hugging Face tokenizer means by \\s. Short enough to list in full.
bool is_whitespace(uint32_t cp) {{
  if (cp < 0x80) return (cp >= 0x09 && cp <= 0x0D) || cp == 0x20;
  switch (cp) {{
    case 0x0085: case 0x00A0: case 0x1680: case 0x2028: case 0x2029:
    case 0x202F: case 0x205F: case 0x3000:
      return true;
    default:
      return cp >= 0x2000 && cp <= 0x200A;
  }}
}}

}}  // namespace lcr
""")

    print(f"wrote {out} ({len(letters)} letter ranges, {len(numbers)} number "
          f"ranges, Unicode {unicodedata.unidata_version})", file=sys.stderr)


if __name__ == "__main__":
    main()
