// Unicode character class predicates used by the pretokenizer regex.
// The tables live in unicode_data.cpp, which is generated by
// tools/gen_unicode_data.py.
#pragma once

#include <cstdint>

namespace lcr {

// Regex \p{L}: general categories Lu, Ll, Lt, Lm, Lo.
bool is_letter(uint32_t codepoint);
// Regex \p{N}: general categories Nd, Nl, No.
bool is_number(uint32_t codepoint);
// Regex \s: the Unicode White_Space property.
bool is_whitespace(uint32_t codepoint);

}  // namespace lcr
